from collections import defaultdict

data = {
  "पाच चिनी भाई_1": "BOOKS/English/5chinese.pdf",
  "पाच चिनी भाई_2": "BOOKS/English/5chinese_t.pdf",
  "THE TWENTY ONE BALLOONS": "BOOKS/English/21balloons.pdf",
  "Mr. Wizard’s": "BOOKS/English/400wizard.pdf",
  "700 SCIENCE EXPERIMENTS FOR EVERYONE": "BOOKS/English/700un1.pdf",
  "CHAPTER XII": "BOOKS/English/700un2.pdf",
  "Letter Written in the Year 2070": "BOOKS/English/2070water.pps",
  "The ABC BUNNY": "BOOKS/English/abcbunny.pdf",
  "The Paper Aeroplane Book": "BOOKS/English/aero.pdf",
  "AHA! ACTIVITIES": "BOOKS/English/ahaact.pdf",
  "AHA! BOOKS!": "BOOKS/English/ahabooks.pdf",
  "FOR YOUR OWN GOOD": "BOOKS/English/alicemiller.pdf",
  "AMOS FORTUNE: FREE MAN": "BOOKS/English/amosfortune.pdf",
  "Anatomy of an Illness": "BOOKS/English/Anatomy.pdf",
  "SECRET OF THE ANDES": "BOOKS/English/andes.pdf",
  "ANNO’S MAGIC SEEDS   -  MITSUMASA ANNO": "BOOKS/English/anno.pdf",
  "How we found about Antarctica": "BOOKS/English/antarcticapix.pdf",
  "THE SPIRIT OF ANT": "BOOKS/English/ants.pdf",
  "The Radient Raindrops of Rajasthan": "BOOKS/English/anupam.pdf",
  "Anything School Can Do You Can Do Better": "BOOKS/English/Anything.pdf",
  "THE ART OF THE STORY-TELLER": "BOOKS/English/art.pdf",
  "The Bicentennial Man": "BOOKS/English/asimov ebook.pdf",
  "HOW DID WE FIND OUT ABOUT THE ATMOSPHERE?": "BOOKS/English/asimovatmosphere.pdf",
  "HOW DID WE FIND OUT ABOUT SUPERCONDUCTIVITY?": "BOOKS/English/asimovsuperconductivity.pdf",
  "HOW DID WE FIND OUT ABOUT THE BRAIN?": "BOOKS/English/asimovbrain.pdf",
  "Asking the Earth": "BOOKS/English/askingtheearth.pdf",
  "How we found about  ATOMS": "BOOKS/English/atomspix.pdf",
  "बच्चे कैसे बनते है": "BOOKS/English/babies.pdf",
  "Significance of Laurie Baker": "BOOKS/English/bakerbhushan.pdf",
  "The Brick Master of Kerala": "BOOKS/English/bakerbrickmaster.pdf",
  "Laurie Baker:A Tribute": "BOOKS/English/bakerburte.pdf",
  "Call a brick wall a brick wall": "BOOKS/English/bakercallabrickabrick.pdf",
  "Architecture for the people ": "BOOKS/English/bakerjogi.pdf",
  "Laurie Baker's creative journey  ": "BOOKS/English/bakerjogi.pdf",
  "Master mason  Volume 24 - Issue 07 :: Apr. 07-20,": "BOOKS/English/bakermastermason.pdf",
  "Architecture for the people": "BOOKS/English/bakerjogi.pdf",
  "Volume 20 - Issue 05,": "BOOKS/English/bakerjogiatul.pdf",
  "Special issue with the Sunday Magazine": "BOOKS/English/bakerownwords.pdf",
  "Here Was a Baker": "BOOKS/English/bakertribute.pdf",
  "The Librarian Of Basra": "BOOKS/English/basra.pdf",
  "The Beautiful Tree": "BOOKS/English/beautifultree.pdf",
  "The Bee and the Rose": "BOOKS/English/bee.pdf",
  "CYBERNETICS OF NATIONAL DEVELOPMENT": "BOOKS/English/beer.pdf",
  "THE SACRED BEETLE & OTHER GREAT ESSAYS IN SCIENCE": "BOOKS/English/beetle.pdf",
  "BAHUROOPE GANDHI": "BOOKS/English/bg.pdf",
  "The Bicycle Story.": "BOOKS/English/bicyclestoryenglish.pdf",
  "The Common Birds Of India.": "BOOKS/English/birds.pdf",
  "How we found about  BLACK HOLES": "BOOKS/English/blackholespix.pdf",
  "ISLAND OF THE BLUE DOLPHINS": "BOOKS/English/bluedolphins.pdf",
  "BOBAK GOAT": "BOOKS/English/bobak.pdf",
  "FROM BONE TO STONE": "BOOKS/English/bonetostone.pdf",
  "THE BOOK OF EXPERIMENTS": "BOOKS/English/bookofexpts.pdf",
  "The Story Book of Science": "BOOKS/English/BookofScience.pdf",
  "Brick Work": "BOOKS/English/brickwork.pdf",
  "The Day of the Bubble": "BOOKS/English/bubble.pdf",
  "BUD, NOT BUDDY": "BOOKS/English/budnotbuddy.pdf",
  "Behind the Bungalow, by EHA": "BOOKS/English/Bungalow.pdf",
  "Butterfly Kisses": "BOOKS/English/butterflykisses.pdf",
  "CADDIE WOODLAWN": "BOOKS/English/caddie.pdf",
  "Number fun with a calendar": "BOOKS/English/calendar.pdf",
  "THE CHEMICAL History Of Candle": "BOOKS/English/candle.pdf",
  "THE CAT WHO WENT TO HEAVEN": "BOOKS/English/catheaven.pdf",
  "THE LIVES OF A CELL": "BOOKS/English/cell.pdf",
  "THE CHANGING NATURE OF MAN": "BOOKS/English/changingman.pdf",
  "CHEAPER BY THE DOZEN": "BOOKS/English/cheaper.pdf",
  "The Chemistry of Everyday Life": "BOOKS/English/chemistryyasmin.pdf",
  "BROTHERS FROM CHICHIBABA": "BOOKS/English/chichihe.pdf",
  "THE TALE OF THE LITTLE RED HEN": "BOOKS/English/chick.pdf",
  "Brother agle,Sister Sky": "BOOKS/English/chiefseattle.pdf",
  "CHILDREN & BALANCES": "BOOKS/English/childandbalance.pdf",
  "CHILDREN AND WATER": "BOOKS/English/childandwater.pdf",
  "CHILD DEVELOPMENT AND EDUCATION": "BOOKS/English/childdevelkind.pdf",
  "Children Play": "BOOKS/English/children play.pdf",
  "CHILDREN OF THE ASHES": "BOOKS/English/childrenoftheashes.pdf",
  "LITTLE CHILDREN HELP": "BOOKS/English/chinese.pdf",
  "CIVIL DISOBEDIENCE IN INDIAN TRADITION": "BOOKS/English/civildharam.pdf",
  "How we found about COMETS": "BOOKS/English/cometspix.pdf",
  "Community Based Biology": "BOOKS/English/communitybiology.pdf",
  "CONCERNING ANIMALS AND OTHER MATTERS": "BOOKS/English/concerninganimals.pdf",
  "How Did We Find About Computers": "BOOKS/English/computerpix.pdf",
  "Where we competed with ourselves": "BOOKS/English/competed.pdf",
  "THE CONTINUUM CONCEPT": "BOOKS/English/conconcept.pdf",
  "MANUAL OF COST CUTS FOR STRONG ACCEPTABLE HOUSING": "BOOKS/English/costcutsbaker.pdf",
  "स्कूल डायरी": "BOOKS/English/countryschooldiary.pdf",
  "CALL IT COURAGE": "BOOKS/English/courage.pdf",
  "FLOWERING  TREES & SHRUBS IN INDIA": "BOOKS/English/cowen.pdf",
  "Creative Writing": "BOOKS/English/creative.pdf",
  "CRISPIN The Cross Of Lead": "BOOKS/English/crispin.pdf",
  "CALCUTTA DIARY": "BOOKS/English/culcuttadairy.pdf",
  "The Culture and Civilisation of Ancient India": "BOOKS/English/cultddk.pdf",
  "Curious George": "BOOKS/English/curiousgeorge.pdf",
  "Danger School": "BOOKS/English/Danger_schoo.pdf",
  "THE DARK FRIGATE": "BOOKS/English/darkfrigate.pdf",
  "The Autobiography of Charles Darwin": "BOOKS/English/darwinauto.pdf",
  "EDUCATION: INTERVIEW": "BOOKS/English/davidrosalind.pdf",
  "Atomic Enegy For India": "BOOKS/English/DDK.pdf",
  "Dr. Damodar Dharmananda Kosambi": "BOOKS/English/ddkbio.pdf",
  "History And Socoety": "BOOKS/English/ddkbomuniv.pdf",
  "Exasperating Essays": "BOOKS/English/ddkee.pdf",
  "D.D. KOSAMBI Combined Methods in Indology and Other Writings": "BOOKS/English/ddkindopartone.pdf",
  "THE HUMP ON NANDI’S BACK": "BOOKS/English/ddknandi.pdf",
  "INDIAN NUMISMATICS": "BOOKS/English/ddknumismatics.pdf",
  "INDIAN": "BOOKS/English/indtales.pdf",
  "SCHOOL IS DEAD": "BOOKS/English/dead.pdf",
  "I have a sister": "BOOKS/English/deaf.pdf",
  "Toying with Science": "BOOKS/English/deccanherald.pdf",
  "How Did We Find Out About: Life In the Sea?": "BOOKS/English/deepseapix.pdf",
  "DEMOCRATISING YOUR School": "BOOKS/English/demoschools.pdf",
  "Deschooling Society": "BOOKS/English/DESCHOOLING.pdf",
  "DESIGN FOR THE REAL WORLD": "BOOKS/English/designvictor.pdf",
  "Democracy and Education: An Introduction to the Philosophy of Education": "BOOKS/English/dewey.pdf",
  "EXPERIENCE & EDUCATION": "BOOKS/English/dewey2.pdf",
  "DICEY’S SONG": "BOOKS/English/diceysong.pdf",
  "How we found about DINOSAURS": "BOOKS/English/dinopix.pdf",
  "How we found about DNA": "BOOKS/English/dnapix.pdf",
  "Dr. DoLittle": "BOOKS/English/dolittle.pdf",
  "DOOR IN THE WALL": "BOOKS/English/doorwall.pdf",
  "THE HUNDRED DRESSES": "BOOKS/English/dresses.pdf",
  "Divaswapna (English translation)": "BOOKS/English/ds.pdf",
  "Make Way For ducklings": "BOOKS/English/ducklings.pdf",
  "Duishen": "BOOKS/English/Duishen.pdf",
  "IN SEARCH FOR THE MEANING OF SCIENCE": "BOOKS/English/dunu.pdf",
  "The Earth is Round": "BOOKS/English/earthisroundplay.pdf",
  "HOW DID WE FIND OUT The Earth Is Round": "BOOKS/English/earthpix.pdf",
  "How we found about EARTHQUAKES": "BOOKS/English/earthquakespix.pdf",
  "Einstein A Passionate Adventure": "BOOKS/English/einstienkosambi.pdf",
  "How we found about ENERGY": "BOOKS/English/energypix.pdf",
  "EarthQuake": "BOOKS/English/earthquake.pdf",
  "How we found about ELECTRICITY": "BOOKS/English/electricitypix.pdf",
  "The Education of the Child by Ellen Key": "BOOKS/English/EllenKey.pdf",
  "Environment And Self-Reliance :": "BOOKS/English/environ.pdf",
  "The Exploring Child": "BOOKS/English/exploringchild.pdf",
  "The Exploring Nature": "BOOKS/English/exploringnature.pdf",
  "CHILDREN OF THE SUMMER": "BOOKS/English/fabrechildren.pdf",
  "FAITHFUL ELEPHANTS": "BOOKS/English/faithelephants.pdf",
  "ARCHITECTURE FOR THE POOR": "BOOKS/English/fathy.pdf",
  "Faithful Elephants": "BOOKS/English/fe.pdf",
  "FOUR AGAINST THE ODDS": "BOOKS/English/fouragainst.pdf",
  "The Fox": "BOOKS/English/fox.pdf",
  "DAVID WIESNER Free Fall": "BOOKS/English/freefall.pdf",
  "Free From School": "BOOKS/English/freefromschool.pdf",
  "FREEDOM--NOT LICENSE": "BOOKS/English/Freeneillfinal.pdf",
  "फुगे का वह दिन": "BOOKS/English/fuggeykadin.pdf",
  "The Funny Little Woman": "BOOKS/English/funnywoman.pdf",
  "THE GATHERING OF DAYS": "BOOKS/English/gatheringdays.pdf",
  "Winner Of The Newbery Medal": "BOOKS/English/gayneck.pdf",
  "How we found about GERMS": "BOOKS/English/germspix.pdf",
  "GERMS TELUGU": "BOOKS/English/germstelegu.pdf",
  "GHOND THE HUNTER": "BOOKS/English/ghond.pdf",
  "THE GENEROUS TREE": "BOOKS/English/givingtree.pdf",
  "COMPULSORY MISEDUCATION": "BOOKS/English/goodman.pdf",
  "GOOD WORK": "BOOKS/English/goodwork.pdf",
  "WHAT HAPPENED IN HISTORY": "BOOKS/English/gordonchilde.pdf",
  "A PREPARATION FOR SCIENCE": "BOOKS/English/gregs.pdf",
  "THE GREY KING": "BOOKS/English/greyking.pdf",
  "Guess What I’m Doing!": "BOOKS/English/guessun.pdf",
  "Hands ON- Ideas And Activities_1": "BOOKS/English/handson1.pdf",
  "Hands ON- Ideas And Activities_2": "BOOKS/English/handson2.pdf",
  "THE HAPPY LION": "BOOKS/English/happylion.pdf",
  "HARI THE JUNGLE LAD": "BOOKS/English/hari.pdf",
  "HATCHET": "BOOKS/English/hatchet.pdf",
  "How Children Fail": "BOOKS/English/HCF.pdf",
  "How Children Learn": "BOOKS/English/hcl.pdf",
  "Canopy Of the Hevens": "BOOKS/English/heavens.pdf",
  "Three Days to See": "BOOKS/English/helenkeller.pdf",
  "THE WAY IT SPOZED TO BE": "BOOKS/English/hendron.pdf",
  "DEAR MR. HENSHAW": "BOOKS/English/henshaw.pdf",
  "MISS HICKORY": "BOOKS/English/hickory.pdf",
  "Thus spake the toymaker": "BOOKS/English/hindujune07.pdf",
  "Hiroshima": "BOOKS/English/hirohersey.pdf",
  "WHAT IS HISTORY": "BOOKS/English/historycarr.pdf",
  "EVERYTHING HAS A HISTORY": "BOOKS/English/historyjbs.pdf",
  "HITTY- HER FIRST HUNDRED YEARS": "BOOKS/English/hitty.pdf",
  "SELECTED LETTERS OF JOHN HOLT-A Life Worth Living": "BOOKS/English/holtletters.pdf",
  "Hope For The Flowers": "BOOKS/English/hopeflowers.pdf",
  "Hot on the Secnt": "BOOKS/English/hotonthescent.pdf",
  "The Hot Seat": "BOOKS/English/hotseat.pdf",
  "HOW YOU BEGAN": "BOOKS/English/howyoubegan.pdf",
  "The Hoshangabad Vigyan": "BOOKS/English/hstppix.pdf",
  "HOW THINGS ARE": "BOOKS/English/hta.pdf",
  "How the Tell the Birds from the Flowers": "BOOKS/English/httbf10h.pdf",
  "Hungry Stones and the Other Stories by Rabindranath Tagore": "BOOKS/English/hungrystones.pdf",
  "IDGAH Festival Of EID": "BOOKS/English/idgah.pdf",
  "INDIAN FAIRY TALES": "BOOKS/English/indtales.pdf",
  "The Insect Man": "BOOKS/English/insectman.pdf",
  "Insult To Intelligence": "BOOKS/English/insult.pdf",
  "The Study Of Indian Hostory": "BOOKS/English/introhisddk.pdf",
  "INVINCIBLE LOUSIA": "BOOKS/English/invincible.pdf",
  "JACOB HAVE I LOVED": "BOOKS/English/jacob.pdf",
  "King Of Children": "BOOKS/English/Janusz.pdf",
  "JATAKA TALES": "BOOKS/English/jataka.pdf",
  "Tyre Fun Playground": "BOOKS/English/jimmy.pdf",
  "Jonathan Livingston Seagull - a story": "BOOKS/English/jls.pdf",
  "I AM JOE’S BODY": "BOOKS/English/joebody.pdf",
  "mutual enrichment amongst emancipatory currents: engaging with its lack− II ": "BOOKS/English/jogin.pdf",
  "Some thoughts Concerning Education": "BOOKS/English/John Locke.pdf",
  "Jolly Family": "BOOKS/English/jollyfamily.pdf",
  "JOY OF MAKING INDIAN TOYS": "BOOKS/English/joyindiantoys.pdf",
  "JOY OF Learning": "BOOKS/English/joynew.pdf",
  "JOY OF LEARNING_01": "BOOKS/English/joythree.pdf",
  "JOY OF LEARNING": "BOOKS/English/joytwo.pdf",
  "JULIE OF THE WOLVES": "BOOKS/English/julie.pdf",
  "The Jungle Book": "BOOKS/English/jungle.pdf",
  "FOR HEAVEN’S SAKE": "BOOKS/English/jvnRD.pdf",
  "Kahani": "BOOKS/English/kahanisample.pdf",
  "KARI THE ELEPHANT": "BOOKS/English/kari.pdf",
  "Learning Science through Activities and Toys": "BOOKS/English/khagol.pdf",
  "KING OF THE WIND": "BOOKS/English/kingofwind.pdf",
  "BRINGING  RAIN  TO  KAPITI  PLAIN": "BOOKS/English/kipat.pdf",
  "BRINGING THE RAIN TO KAPITI PLAIN": "BOOKS/English/kipatcolour.pdf",
  "THE ELEPHANT’S CHILD": "BOOKS/English/kiplingcolour.pdf",
  "The Child's Language And The Teacher - A Handbook": "BOOKS/English/kk.pdf",
  "How Did We Find About Lasers?": "BOOKS/English/laserpix.pdf",
  "THE LAST FLOWER": "BOOKS/English/lastflower.pdf",
  "LEARNING ALL THE TIME": "BOOKS/English/latt.pdf",
  "IUCAA loads website with 700 books": "BOOKS/English/learnerslibrary.pdf",
  "FUN WITH LEAVES": "BOOKS/English/leaves.pdf",
  "A. S. Makarenko Lecture to Parents": "BOOKS/English/Lectures to Parents.pdf",
  "Letter To Teacher": "BOOKS/English/letter.pdf",
  "IT'S LIKE THIS CAT": "BOOKS/English/likethiscat.pdf",
  "When Reich wrote Listen, Little Man!": "BOOKS/English/listen.pdf",
  "THE LITTLE Toys": "BOOKS/English/Little_Toys.pdf",
  "THE LITTLE PRINCE": "BOOKS/English/littleprince.pdf",
  "Little Rabbit": "BOOKS/English/littlestrabbit.pdf",
  "Little Science": "BOOKS/English/LITTLESCIENCE.pdf",
  "The Lives of Children": "BOOKS/English/LivesofChildren.pdf",
  "LOW-COST, NO-COST": "BOOKS/English/lowcostnocost.pdf",
  "Aunt Lulu": "BOOKS/English/lulu.pdf",
  "Madness Story": "BOOKS/English/Madness.pps",
  "ADVENTURES IN EDUCATION": "BOOKS/English/malting.pdf",
  "BRAHMA'S   HAIR": "BOOKS/English/manekatrees.pdf",
  "MANIAC MAGEE": "BOOKS/English/maniacmagee.pdf",
  "*The Story of Mankind": "BOOKS/English/mankind.pdf",
  "MARJORIE SYKES": "BOOKS/English/marjorie.pdf",
  "Science Puzzlers": "BOOKS/English/martingardner.pdf",
  "THE MASS PSYCHOLOGY OF FASCISM": "BOOKS/English/massreich.pdf",
  "MATCHSTICK MATCHING": "BOOKS/English/match puzzles.pdf",
  "The Matchlock Gun": "BOOKS/English/matchlock.pdf",
  "Trick, Games and puzzles with Matches": "BOOKS/English/matchplay.pdf",
  "MATCHSTICK MODELS AND OTHER SCIENCE EXPERIMENTS": "BOOKS/English/Matchstick.pdf",
  "Why I am a Materialist": "BOOKS/English/materialist.pdf",
  "How Children Learn Mathematics": "BOOKS/English/mathsliebeck.pdf",
  "100 Beautiful Trees Of India": "BOOKS/English/mccann.pdf",
  "THE MIDWIFE'S APPRENTICE": "BOOKS/English/midwife.pdf",
  "OBEDIENCE TO AUTORITY": "BOOKS/English/milgram.pdf",
  "The Militant Observer": "BOOKS/English/MilitantObserver.pdf",
  "MILLIONS OF CATS": "BOOKS/English/millionsofcats.pdf",
  "MIRACLES ON MAPLE HILL": "BOOKS/English/miracles.pdf",
  "CHILDREN, MIRRORS & REFLECTION": "BOOKS/English/mirror.pdf",
  "MISEDUCATION": "BOOKS/English/miseducation.pdf",
  "MISSING MAY": "BOOKS/English/missingmay.pdf",
  "DR. MONTESSORI GIVING A LESSON IN TOUCHING GEOMETRICAL INSETS": "BOOKS/English/montessori.pdf",
  "ThumbPrints": "BOOKS/English/morethumbprints.pdf",
  "My Friend Mr. Leakey,": "BOOKS/English/mrleaky.pdf",
  "MUD": "BOOKS/English/mud_english.pdf",
  "THE BIOGRAPHY OF A BABY": "BOOKS/English/mwshinn.pdf",
  "Myth and Reality Studies in the formation of Indian Culture": "BOOKS/English/mythandreality.pdf",
  "THE STORY OF NAI TALIM": "BOOKS/English/naitalem.pdf",
  "Nandi ki Peeth Ka Kubad": "BOOKS/English/nandihindi.pdf",
  "PERSONAL REMINSCENCES of Prof. D. D. Kosambi": "BOOKS/English/nene.pdf",
  "NEVER TOO LATE": "BOOKS/English/nevertoolate.pdf",
  "ENERGY And Self-Reliance": "BOOKS/English/newenergy.pdf",
  "NIGHT": "BOOKS/English/night.pdf",
  "WILD FLOWERS OF INDIA": "BOOKS/English/nimrethanda.pdf",
  "Number Fun with Calendar": "BOOKS/English/numberfun.pdf",
  "Sankhya Jagat Me Khel Kud": "BOOKS/English/numberlandh.pdf",
  "How we found about NUMBERS": "BOOKS/English/numberspix.pdf",
  "Dasmselflies": "BOOKS/English/odonatesdamselflies.pdf",
  "Dragonflies": "BOOKS/English/odonatesdragonflies.pdf",
  "Dragonflies And Dasmselflies Of Peninsukar India": "BOOKS/English/odonatesintro.pdf",
  "How we found about  OIL": "BOOKS/English/oilpix.pdf",
  "The One Straw Revoution": "BOOKS/English/onestraw.pdf",
  "Our India- 1953": "BOOKS/English/ourindia.pdf",
  "How we found about OUTER SPACE": "BOOKS/English/outerspacepix.pdf",
  "OUT OF THE DUST": "BOOKS/English/outofdust.pdf",
  "PanchayatRaj And India's Polity": "BOOKS/English/panchayatdharam.pdf",
  "MATHEMATICS THROUGH PAPER FOLDING": "BOOKS/English/paperfolding.pdf",
  "A TREATISE ON PARENTS AND CHILDREN": "BOOKS/English/Parents_and_Children.pdf",
  "FORTY  COMMON  INDIAN  TREES": "BOOKS/English/parkertrees.pdf",
  "Exerises": "BOOKS/English/paulofriere.pdf",
  "The Peace Poem": "BOOKS/English/peacepoem.pdf",
  "Predagogy": "BOOKS/English/pedagogy.pdf",
  "The Pinkish,Purplish Bluish Egg": "BOOKS/English/peetegg.pdf",
  "Periodic Table Of the Elements": "BOOKS/English/periodictableblackwhite.pdf",
  "UNDERSTANDING PHYSICS - Part 1": "BOOKS/English/phys1.pdf",
  "UNDERSTANDING PHYSICS 2": "BOOKS/English/phys2.pdf",
  "UNDERSTANDING PHYSICS": "BOOKS/English/phys3.pdf",
  "PHYSICS EXPERIMENTS FOR CHILDREN": "BOOKS/English/physicsexperiments.pdf",
  "THE STORY OF PING": "BOOKS/English/ping.pdf",
  "Nature Guide Common Trees Of India ": "BOOKS/English/pippatrees.pdf",
  "Pippi Longstocking": "BOOKS/English/Pippi.pdf",
  "RESOURCE MATERIAL FOR MATHEMATICS CLUB ACTIVITIES": "BOOKS/English/pkshindu.pdf",
  "The Man Who Planted Trees": "BOOKS/English/plantedtrees.pdf",
  "Oh Say can You Seed?": "BOOKS/English/plantsseuss.pdf",
  "How Did We Find About Pluto": "BOOKS/English/plutopix.pdf",
  "Science Through Postcard": "BOOKS/English/postcard.pdf",
  "The Web Of Life": "BOOKS/English/pramukh.pdf",
  "ELEVEN STORIES BY PREMCHAND": "BOOKS/English/premchand11.pdf",
  "NO FOUL SMELLING LAB THIS": "BOOKS/English/prithviht.pdf",
  "PUMPS FROM THE DUMP": "BOOKS/English/pumps.pdf",
  "RABBIT HILL": "BOOKS/English/rabbithill.pdf",
  "Sachitra Kahaniya": "BOOKS/English/radlovcolour.pdf",
  "Railgadi": "BOOKS/English/railgadihineng.pdf",
  "Rats": "BOOKS/English/rats.pdf",
  "READING": "BOOKS/English/readingfrank.pdf",
  "The Red Balloon": "BOOKS/English/redballoon.pdf",
  "The Red Balloon_hindi & English": "BOOKS/English/redballoonhineng.pdf",
  "Riddles in Your Teacup": "BOOKS/English/riddlesteacup.pdf",
  "RIFLES FOR WATIE": "BOOKS/English/rifles.pdf",
  "ON BEING THE RIGHT SIZE": "BOOKS/English/rightsize.pdf",
  "A CONVERSATION WITH THE CHIEF OF THE GUBERNIA DEPARTMENT OF PUBLIC EDUCATION ": "BOOKS/English/road1.pdf",
  "The Road to Life: An Epic of Education": "BOOKS/English/road2.pdf",
  "ROLLER SKATES": "BOOKS/English/rollerskates.pdf",
  "ROLL OF THUNDER HEAR MY CRY": "BOOKS/English/rollofthunder.pdf",
  "ROMPING IN NUMBERLAND": "BOOKS/English/rompinginnumberlandeng.pdf",
  "Roving East And Roving West": "BOOKS/English/roving.pdf",
  "Rubbish By Baker": "BOOKS/English/rubbishbaker.pdf",
  "The Runaway Bunny": "BOOKS/English/runawaybunny.pdf",
  "Rural Community Buildings": "BOOKS/English/ruralcombaker.pdf",
  "Rural House Plans": "BOOKS/English/ruralhouseplans.pdf",
  "True Anti Nuke Story Of Sadako": "BOOKS/English/sadako.pdf",
  "Sadako Aur Kagaj Ke Pakshi": "BOOKS/English/sadakohindi.pdf",
  "RICHARD ST. BARBE BAKER: Man Of The Trees": "BOOKS/English/saintbaker.pdf",
  "Blueberries For Sal": "BOOKS/English/sal.pdf",
  "Ecological Sanitation": "BOOKS/English/sanitation.pdf",
  "COMMON TREES": "BOOKS/English/santapau.pdf",
  "SARAH, PLAIN AND TALL": "BOOKS/English/sarah.pdf",
  "My Country School Diary": "BOOKS/English/SchoolDiary.pdf",
  "School Society The Future": "BOOKS/English/schoolidac.pdf",
  "Indian Science And Technology In 18th Century": "BOOKS/English/sciencedharam.pdf",
  "Self Respecting Child": "BOOKS/English/selfrespectingchild.pdf",
  "Brothers From Chichibaba": "BOOKS/English/sengupta.pdf",
  "SHADOW OF A BULL": "BOOKS/English/shadowbull.pdf",
  "SHILOH": "BOOKS/English/shiloh.pdf",
  "SHIN’S TRICYCLE": "BOOKS/English/shin.pdf",
  "SIMPLE SCIENCE EXPERIMENTS": "BOOKS/English/simsciexpts.pdf",
  "SMALL IS BEAUTIFUL": "BOOKS/English/small.pdf",
  "SMOKY THE COWHORSE": "BOOKS/English/smoky.pdf",
  "Solar Power": "BOOKS/English/solarpix.pdf",
  "Sukha Pani Bachayiye": "BOOKS/English/sookha.pdf",
  "SOUNDER": "BOOKS/English/sounder.pdf",
  "SPECIAL OLYMPICS": "BOOKS/English/special.pdf",
  "1001 USES OF THE HUNDRED SQUARE:": "BOOKS/English/squaresall.pdf",
  "SILENT SPRING": "BOOKS/English/ss.pdf",
  "Science, Society & Peace": "BOOKS/English/sspkosambi.pdf",
  "STAYING ALIVE": "BOOKS/English/stayingalive.pdf",
  "Story Of Chemistry": "BOOKS/English/storyofchemistry.pdf",
  "STRAWBERRY GIRL": "BOOKS/English/strawberry.pdf",
  "STRING Games": "BOOKS/English/stringgames.pdf",
  "Study Of Fairy Tales": "BOOKS/English/studyfairy.pdf",
  "Joy Of Making Indian Toys": "BOOKS/English/sudarshan.pdf",
  "INDIAN TOYS & TOY MAKERS:": "BOOKS/English/sudarshan2.pdf",
  "Summerhill": "BOOKS/English/summerhill.pdf",
  "Sunshine": "BOOKS/English/sunshinepix.pdf",
  "LOOKING AT THE BODY": "BOOKS/English/suzukibody.pdf",
  "LOOKING AT PLANTS": "BOOKS/English/suzukiplants.pdf",
  "AN EXPERIMENT IN EDUCATION": "BOOKS/English/sybil.pdf",
  "SYLVIA!": "BOOKS/English/sylviabio.pdf",
  "TEACHING AS A SUBVERSIVE ACTIVITY": "BOOKS/English/taasa.pdf",
  "PIONEER IN EDUCATION - RABINDRANATH TAGORE": "BOOKS/English/tagore.pdf",
  "Teachers as Transformers: Learning from outstanding primary school teachers": "BOOKS/English/tat.pdf",
  "The Children’s Story…": "BOOKS/English/tcs.pdf",
  "Sylvia Astone_Warner The Testament of Inspired Teacher": "BOOKS/English/Teacher.pdf",
  "TEACH YOUR OWN": "BOOKS/English/teachyourown.pdf",
  "HOW TO TELL STORIES TO CHILDREN": "BOOKS/English/tell stories.pdf",
  "The Fire of Hiroshima": "BOOKS/English/tfoh.pdf",
  "THE GIVER": "BOOKS/English/thegiver.pdf",
  "THIMBLE SUMMER": "BOOKS/English/thimble.pdf",
  "Three Promises For You:": "BOOKS/English/threepromises.pdf",
  "THUMBPRINTS": "BOOKS/English/THUMBPRINTS.pdf",
  "THE Idiot Teacher": "BOOKS/English/tit.pdf",
  "Ten Little Fingers": "BOOKS/English/tlf120.pdf",
  "To Know A Fly": "BOOKS/English/Toknowafly.pdf",
  "Tolstoy as a Schoolmaster": "BOOKS/English/tolstoy.pdf",
  "GIVE US THE TOOLS": "BOOKS/English/tools.pdf",
  "The Little girl at the window": "BOOKS/English/Tottochan.pdf",
  "The Little girl at the window Totto Chan": "BOOKS/English/tottochan_t.pdf",
  "Toy Treasures": "BOOKS/English/ToyTreasure.pdf",
  "Essay On Tradition, Recovery And Freedom": "BOOKS/English/traditiondharam.pdf",
  "The Toy Bag": "BOOKS/English/Toy_bag.pdf",
  "Trashcan Kids": "BOOKS/English/Trashcan Kids.pdf",
  "Sharing Treasures": "BOOKS/English/treasures.pdf",
  "Tree Story": "BOOKS/English/Tree.pps",
  "OUR TREE NEIGHBOURS": "BOOKS/English/treesncert.pdf",
  "TRIBES ON MY FRONTIER_2": "BOOKS/English/tribes2eha.pdf",
  "TRIBES ON MY FRONTIER": "BOOKS/English/tribeseha.pdf",
  "Science & Human Progress": "BOOKS/English/tributes.pdf",
  "THE TRUMPETER OF KRAKOW": "BOOKS/English/trumpeter.pdf",
  "WALK TWO MOONS": "BOOKS/English/twomoon.pdf",
  "THE UNDERACHIEVING SCHOOL": "BOOKS/English/underachieving.pdf",
  "Understanding Children": "BOOKS/English/Understanding Children.pdf",
  "Preparation For Understanding": "BOOKS/English/Understanding.pdf",
  "Science And Technology Education": "BOOKS/English/unescoresourcekit.pdf",
  "The Universe?": "BOOKS/English/universepix.pdf",
  "To Children I Give My Heart": "BOOKS/English/Vasily.pdf",
  "PARTICIPATORY SCIENCE EXHIBITS": "BOOKS/English/vikramexhibits.pdf",
  "MOVED BY LOVE": "BOOKS/English/vinoba.pdf",
  "How we found about VITAMINS": "BOOKS/English/vitaminspix.pdf",
  "SCIENCE EXPERIMENTS & AMUSEMENTS FOR CHILDREN": "BOOKS/English/vivian.pdf",
  "How did we find about VOLCANOES?": "BOOKS/English/volcanoespix.pdf",
  "The Second Book Of Experiments": "BOOKS/English/vries2.pdf",
  "THE MATHS TEACHER’S HANDBOOK": "BOOKS/English/vsomaths.pdf",
  "VSO The Science Teachers’ Handbook": "BOOKS/English/vsoscience.pdf",
  "How To Make And Use Visual Aids": "BOOKS/English/vsovisualnew.pdf",
  "I WAS WALKING Down The Road": "BOOKS/English/walkingroad.pdf",
  "WHAT DO I DO Monday?": "BOOKS/English/whatdoidomonday.pdf",
  "What Me A Racist?": "BOOKS/English/whatmeracist.pdf",
  "THE WHEEL ON THE SCHOOL": "BOOKS/English/wheel.pdf",
  "MY FEET ARE THE WHEEL-CHAIR": "BOOKS/English/wheelchairhineng.pdf",
  "THE WHIPPING BOY": "BOOKS/English/whipping.pdf",
  "THE WHITE STAG": "BOOKS/English/whitestag.pdf",
  "WALKING THE WILD PATH": "BOOKS/English/wildpath.pdf",
  "THE WITCH OF BLACKBIRD POND": "BOOKS/English/witch.pdf",
  "WHAT IS WORTH TEACHING?": "BOOKS/English/worthteaching.pdf",
  "What's Wrong With The World": "BOOKS/English/wrong.pdf",
  "The Wump World": "BOOKS/English/wump.pdf",
  "YOUNG FU OF THE UPPER YANGTZE": "BOOKS/English/yangtze.pdf",
  "YUGANTA": "BOOKS/English/yuganta.pdf",
  "ZELLA Zack And Zoidac": "BOOKS/English/zella.pdf",
  "ZEN FLESH, ZEN BONES": "BOOKS/English/zen.pdf"
}


# Detect duplicates by value
from collections import defaultdict

value_to_keys = defaultdict(list)
for key, value in data.items():
    value_to_keys[value].append(key)

# Find duplicates
duplicates = {value: keys for value, keys in value_to_keys.items() if len(keys) > 1}

print(duplicates)
